package main

import (
	"log"
	"net/http"

	"github.com/neotylor/go-lang-learning/tree/master/10-projects/web-api/go_task_manager_api/database"
	"github.com/neotylor/go-lang-learning/tree/master/10-projects/web-api/go_task_manager_api/models"
	"github.com/neotylor/go-lang-learning/tree/master/10-projects/web-api/go_task_manager_api/routes"

	_ "github.com/neotylor/go-lang-learning/tree/master/10-projects/web-api/go_task_manager_api/docs" // docs generated by swag

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title           Go Task Manager API
// @version         1.0
// @description     This is a task management API server.
// @host            localhost:8080
// @BasePath        /

func main() {
	database.Connect()     // Step 2: Connect to MySQL database
	models.InitTaskModel() // Step 3: Migrate Task model
	models.InitUserModel() // Step 4: Migrate User model

	r := mux.NewRouter()
	routes.RegisterAllRoutes(r) // Register everything from one place

	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	log.Println("Server starting at http://localhost:8080")
	http.ListenAndServe(":8080", r)
}
